add missing urlparse imports
Was getting these import errors on Python 3.8.2:

    Traceback (most recent call last):
      File "api.py", line 118, in get
        row = self.__call(API_URL, params).read()
      File "api.py", line 102, in __call
        url = '%s?%s' % (url, urllib.parse.urlencode(OrderedDict(
    AttributeError: module 'urllib' has no attribute 'parse'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "api.py", line 207, in <module>
        test_rtm()
      File "api.py", line 203, in test_rtm
        print("Echo?", rtm.test.echo())
      File "api.py", line 179, in <lambda>
        return lambda **params: self.__call(
      File "api.py", line 190, in __call
        return self.rtm.get(method, auth_required, model_cls, **params)
      File "api.py", line 120, in get
        raise RTMSystemError('Cannot connect RTM.', ERRCODE_NETWORK)
    milky.error.RTMSystemError: Cannot connect RTM. (-10)